apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.queryServiceConfig.name }}
  labels:
    release: {{ .Release.Name }}
data:
  application.conf: |-
    service.config = {
      tenantColumnName = "{{ .Values.queryServiceConfig.data.tenantColumnName }}"
      clients = [
        {
          type = zookeeper
          connectionString = "{{ .Values.queryServiceConfig.data.zookeeperConnectionString }}"
        }
      ]
      {{- if .Values.handlers }}
      queryRequestHandlersConfig = [
      {{- range .Values.handlers }}
        {
{{ tpl . $ | indent 10 }}
        }
      {{- end }}
      {{- range .Values.extraHandlers }}
        {
{{ tpl . $ | indent 10 }}
        }
      {{- end }}
      ]
      {{- end }}
    }